### ISSUE TITLE
Condition for %polarizability

### ISSUE THREAD

**Issue by sqamara** [sqamara/mbpol_openmm_plugin#1]
In the i-TTM xml we want an option to specify a parameter for percent polarizability (100 or 50/1 or .5) which will define the appropriate values for the dampingfactor and polarizability within the MBPolElectrostaticsForce part of the xml and can also be used to choose the d6, a and b tables with the python script of the xml.

here is a gist with the code with parameters for both 100 and 50 https://gist.github.com/sqamara/0c7162bf58481e82332c

**Comment by sqamara** [comment]
@zonca

**Comment by zonca** [comment]
@sqamara I think the easiest is just to have 2 different xml one for full and one for 50% polarizability.
The user can then choose the best one.

**Comment by zonca** [comment]
@sqamara if it is not too complicated, it would be nice to have a simple Python script or a notebook that generates the 2 xml files from the same template. so that we do modifications only to the template and then run the script to generate the 2 (or 3) versions

**Comment by sqamara** [comment]
@zonca  Okay I don't think that will be too difficult.  However we would still need 2 (or 3) versions of the c6, a and b tables because they are generated independently of the percent polarizapility. Mark says that there would need to be a flag to choose the correct set.   Is that okay?

**Comment by zonca** [comment]
I think that if most of the time people are going to run with a set of
default parameters then it is better to just have different XML file for
each configuration. Anyway most of the time people will be using the
default XML and we make sure that this is kept as simple as possible.

You said if we have a parameter that it is commonly customized then it
makes sense to add a global configuration parameters to the force field.

**Comment by sqamara** [comment]
addressed here
https://github.com/sqamara/mbpol_openmm_plugin/commit/721e52e7208139188abeac6e29c89c64d3b15c76
